# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
  Hiking from Cape Point to Kosi Bay
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.cape2kosi.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown

maps_api_key: AIzaSyAm9YyAuTKP_n5Tc1LIYvVW2NWSCHpRHlY